--- # django/tasks/static.yml

- name: create static folder
  file: path={{ django_static_path }} state=directory mode=0775
        owner=www-data group=www-data
  become: yes

- name: collect static
  django_manage: command=collectstatic app_path={{ build }}
                 virtualenv={{ virtualenv }}
  become: yes

- name: set static permissions for folders
  command: find {{ django_static_path }} -type d -exec chmod -c 0775 {} \;
  register: chmod_result
  changed_when: "chmod_result.stdout != \"\""
  become: yes

- name: set static permissions for files
  command: find {{ django_static_path }} -type f -exec chmod -c 0664 {} \;
  register: chmod_result
  changed_when: "chmod_result.stdout != \"\""
  become: yes
